name: Deploy docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*' 
jobs:
  public socker conatiner:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repo
      - uses: actions/checkout@master
      
      # Login to dockerhub        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}         
          
      # Setup Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1      
        
      #Setup bot configuration
      - name: Setup env file
        run: |
          touch .env
          echo AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID >> .env
          echo AUTH0_DOMAIN=$AUTH0_DOMAIN >> .env
          echo AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET >> .env
          echo SESSION_SECRET=$SESSION_SECRET >> .env
          echo AUTH0_CALLBACK_URL=http://devenv.westeurope.cloudapp.azure.com:4000/callback >> .env
          echo MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING >> .env
        env:
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          
      # Build and push image
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: augustogallitri/notes-app:latest
